apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps.yaml
  - postgres-statefulset.yaml
  - pgbouncer-deployment.yaml
  - redis-statefulset.yaml
  - rabbitmq-statefulset.yaml
  - opensearch-statefulset.yaml
