apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: ecommerce
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
          ports:
            - containerPort: 5672   # AMQP
            - containerPort: 15672  # management UI
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          startupProbe:
            exec:
              command: ['rabbitmq-diagnostics', 'ping']
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 18
          livenessProbe:
            exec:
              command: ['rabbitmq-diagnostics', 'ping']
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 4
          readinessProbe:
            exec:
              command: ['rabbitmq-diagnostics', 'ping']
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ecommerce
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
