apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-pdb.yaml
  - gateway-pdb.yaml
  - auth-service-pdb.yaml
  - postgres-pdb.yaml
  - redis-pdb.yaml
  - rabbitmq-pdb.yaml
