apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

# Build on top of the base manifests.
resources:
  - ../../base
  # Local-only services not needed in staging/production.
  - additional/jaeger.yaml
  - additional/mailpit.yaml

patches:
  # Scale all Deployments to 1 replica in local dev to save memory.
  - path: patches/scale-down.yaml
    target:
      kind: Deployment

# Override image tags for local builds.
# CI will override these with the actual SHA tag.
images:
  - name: ghcr.io/shubhamshekhar23/ecommerce-monorepo/backend
    newTag: local
  - name: ghcr.io/shubhamshekhar23/ecommerce-monorepo/auth-service
    newTag: local
  - name: ghcr.io/shubhamshekhar23/ecommerce-monorepo/gateway
    newTag: local
  - name: ghcr.io/shubhamshekhar23/ecommerce-monorepo/search-service
    newTag: local
  - name: ghcr.io/shubhamshekhar23/ecommerce-monorepo/notification-service
    newTag: local
