apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-ingress.yaml
  - gateway.yaml
  - backend.yaml
  - auth-service.yaml
  - search-service.yaml
  - notification-service.yaml
  - analytics-service.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - opensearch.yaml
