apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pgbouncer-ingress
spec:
  podSelector:
    matchLabels:
      app: pgbouncer
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
        - podSelector:
            matchLabels:
              app: auth-service
      ports:
        - port: 6432
    - from:
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 9127
