apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rabbitmq-ingress
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
        - podSelector:
            matchLabels:
              app: notification-service
        - podSelector:
            matchLabels:
              app: auth-service
      ports:
        - port: 5672   # AMQP
        - port: 15672  # management UI (internal access only)
