apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-search-service-ingress
spec:
  podSelector:
    matchLabels:
      app: search-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gateway
      ports:
        - port: 3005
