apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - network-policies/
  - pdb/
  - infra/
  - backend/
  - auth-service/
  - gateway/
  - search-service/
  - notification-service/
  - analytics-service/
  - ingress/
  - monitoring/
  - jobs/
